DADOS_INICIAIS = {
    "dinheiro": 10000,
    "populacao": 100,
    "capacidade_populacional": 140,
    "empregos": 30,
    "educacao": 50,
    "saude": 50,
    "energia": 50,
    "agua": 75,
    "poluicao": 10,
    "qualidade_vida": 50,
    "rodada": 1,
    "max_rodadas": 20,
}

REGRAS_ECONOMIA = {
    "producao_por_trabalhador": 180,
    "aliquota_impostos": 0.12,
    "custo_servicos_por_habitante": 9,
    "bonus_qualidade_por_educacao": 0.04,
    "bonus_qualidade_por_saude": 0.04,
    "penalidade_qualidade_por_poluicao": 0.05,
    "crescimento_populacional_base": 3,
    "limite_alerta_recurso": 25,
    "rodadas_em_crise_para_derrota": 3,
}

CONSTRUCOES = {
    "casa": {
        "nome": "Casa",
        "custo": 900,
        "manutencao": 25,
        "capacidade_populacional": 25,
        "populacao": 8,
        "energia": -3,
        "agua": -4,
        "qualidade_vida": 1,
        "descricao": "Aumenta a capacidade da cidade e gera IPTU indiretamente.",
    },
    "escola": {
        "nome": "Escola",
        "custo": 2000,
        "manutencao": 160,
        "empregos": 5,
        "educacao": 8,
        "energia": -4,
        "agua": -3,
        "qualidade_vida": 3,
        "descricao": "Melhora a educação e ajuda a produtividade no longo prazo.",
    },
    "hospital": {
        "nome": "Hospital",
        "custo": 2800,
        "manutencao": 230,
        "empregos": 8,
        "saude": 10,
        "energia": -6,
        "agua": -5,
        "qualidade_vida": 4,
        "descricao": "Aumenta saúde, qualidade de vida e segurança social.",
    },
    "parque": {
        "nome": "Parque",
        "custo": 1200,
        "manutencao": 70,
        "poluicao": -8,
        "qualidade_vida": 6,
        "descricao": "Reduz poluição e deixa a cidade mais agradável.",
    },
    "comercio": {
        "nome": "Comercio",
        "custo": 1600,
        "manutencao": 90,
        "empregos": 14,
        "energia": -5,
        "agua": -3,
        "qualidade_vida": 2,
        "atividade_economica": 850,
        "descricao": "Cria empregos e aumenta a arrecadação por serviços.",
    },
    "fabrica": {
        "nome": "Fabrica",
        "custo": 2600,
        "manutencao": 180,
        "empregos": 28,
        "energia": -12,
        "agua": -8,
        "poluicao": 12,
        "atividade_economica": 1800,
        "descricao": "Gera muitos empregos, mas aumenta poluição e consumo.",
    },
    "estacao_agua": {
        "nome": "Estacao de agua",
        "custo": 2200,
        "manutencao": 140,
        "agua": 18,
        "saude": 3,
        "empregos": 4,
        "descricao": "Melhora o abastecimento e reduz riscos de saúde.",
    },
    "usina_solar": {
        "nome": "Usina solar",
        "custo": 2400,
        "manutencao": 110,
        "energia": 20,
        "empregos": 4,
        "poluicao": -2,
        "descricao": "Aumenta energia com pouco impacto ambiental.",
    },
}

EVENTOS = [
    {
        "id": "seca",
        "titulo": "Seca",
        "descricao": "A falta de chuva reduziu os reservatorios da cidade.",
        "chance": 14,
        "efeitos": {"agua": -12, "saude": -2, "qualidade_vida": -3},
    },
    {
        "id": "crescimento",
        "titulo": "Crescimento economico",
        "descricao": "Novos investidores se interessaram pela cidade.",
        "chance": 12,
        "efeitos": {"dinheiro": 600, "empregos": 6, "qualidade_vida": 1},
    },
    {
        "id": "epidemia",
        "titulo": "Epidemia",
        "descricao": "Um surto aumentou a pressao sobre o sistema de saude.",
        "chance": 10,
        "efeitos": {"saude": -9, "qualidade_vida": -4, "dinheiro": -350},
    },
    {
        "id": "protestos",
        "titulo": "Protestos",
        "descricao": "Moradores reclamam da queda na qualidade de vida.",
        "chance": 11,
        "efeitos": {"qualidade_vida": -5, "dinheiro": -250},
    },
    {
        "id": "mutirao",
        "titulo": "Mutirao ambiental",
        "descricao": "A comunidade ajudou a recuperar areas verdes.",
        "chance": 10,
        "efeitos": {"poluicao": -6, "qualidade_vida": 3},
    },
]
